-- =============================================================================
-- all-in-one.sql (auto-generated by scripts/build-all-in-one-sql.mjs)
-- Bundles supabase/steps/01..08 into a single SQL file for one-shot deploy.
-- After editing any step file, run `node scripts/build-all-in-one-sql.mjs`
-- and paste the regenerated file into Supabase SQL Editor.
-- =============================================================================

-- >>>>>> 01-extensions-and-helpers.sql (2.3 kB) >>>>>>
-- =============================================================================
-- Step 01 / 07 — Extensions + helper functions
-- =============================================================================
-- Paste this into Supabase Dashboard -> SQL Editor and Run.
-- Safe to re-run: every CREATE uses IF NOT EXISTS or OR REPLACE.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 0. Extensions
-- ---------------------------------------------------------------------------
create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- 1. Helper: admin lookup by email
-- ---------------------------------------------------------------------------
-- Two admin emails are hard-coded to match lib/admin.ts on the client.
-- Update both in lockstep when the allowlist changes.
create or replace function public.is_admin_email()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select lower(coalesce(
    (select email from auth.users where id::text = auth.uid()::text),
    ''
  )) in ('mr.hamzik1026@gmail.com', 'nabis95@gmail.com');
$$;

revoke all on function public.is_admin_email() from public;
grant execute on function public.is_admin_email() to authenticated, anon;

-- ---------------------------------------------------------------------------
-- 2. Convenience: cast auth.uid() to uuid explicitly
-- ---------------------------------------------------------------------------
-- In some Supabase setups auth.uid() returns text; the wrapper below
-- guarantees a uuid return type and is used by all RLS policies in step 05.
-- plpgsql + exception handler so an invalid/null auth.uid() returns
-- the all-zeros UUID (matches the behaviour of the literal cast).
create or replace function public.uid() returns uuid
language plpgsql
stable
as $$
declare
  raw text;
begin
  raw := auth.uid();
  if raw is null or raw = '' then
    return '00000000-0000-0000-0000-000000000000'::uuid;
  end if;
  return raw::uuid;
exception when invalid_text_representation then
  return '00000000-0000-0000-0000-000000000000'::uuid;
end;
$$;

grant execute on function public.uid() to authenticated, anon;
-- <<<<<< 01-extensions-and-helpers.sql <<<<<<

-- >>>>>> 02-tables.sql (7.2 kB) >>>>>>
-- =============================================================================
-- Step 02 / 07 — Core tables (user_profiles, profiles, certificates, reviews, complaints)
-- =============================================================================
-- Paste into SQL Editor and Run.
-- After this step you should have 5 tables in the Table Editor.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- user_profiles — per-user account metadata
-- ---------------------------------------------------------------------------
create table if not exists public.user_profiles (
  id              uuid primary key references auth.users(id) on delete cascade,
  email           text not null,
  full_name       text not null default '',
  avatar_url      text not null default '',
  phone           text not null default '',
  is_admin        boolean not null default false,
  is_blocked      boolean not null default false,
  status_override text,
  gender          text check (gender in ('male', 'female')),
  birth_date      date,
  birth_year      integer,
  settlement      text default 'Самашки',
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists idx_user_profiles_email on public.user_profiles (lower(email));

-- updated_at trigger
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_user_profiles_updated on public.user_profiles;
create trigger trg_user_profiles_updated
  before update on public.user_profiles
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- profiles — public catalogues
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
  id                       text primary key,
  owner_id                 uuid references public.user_profiles(id) on delete cascade,
  full_name                text not null default '',
  avatar_url               text not null default '',
  photos                   jsonb not null default '[]'::jsonb,
  is_specialist            boolean not null default false,
  is_personal              boolean not null default false,
  profession_category      text,
  profession_title         text,
  experience               text,
  experience_start         date,
  experience_end           date,
  experience_current       boolean not null default false,
  bio                      text not null default '',
  workplace_address        text not null default '',
  workplace_coords         jsonb not null default '{"lat":43.288024,"lng":45.298989}'::jsonb,
  rating                   numeric(3,1) not null default 0,
  review_count             integer not null default 0,
  phone                    text not null default '',
  hide_phone               boolean not null default false,
  same_as_phone_whatsapp   boolean not null default true,
  whatsapp                 text,
  telegram                 text,
  video_url                text,
  is_verified              boolean not null default false,
  verification_status      text not null default 'none'
    check (verification_status in ('none', 'pending', 'verified', 'rejected')),
  is_admin                 boolean not null default false,
  is_hidden                boolean not null default false,
  is_banned                boolean not null default false,
  work_days                jsonb,
  work_hours_start         text,
  work_hours_end           text,
  break_start              text,
  break_end                text,
  is_flexible_schedule     boolean not null default false,
  gender                   text check (gender in ('male', 'female')),
  birth_date               date,
  settlement               text default 'Самашки',
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now()
);

create index if not exists idx_profiles_owner_id        on public.profiles (owner_id);
create index if not exists idx_profiles_is_hidden       on public.profiles (is_hidden) where not is_hidden;
create index if not exists idx_profiles_specialist      on public.profiles (is_specialist);
create index if not exists idx_profiles_verif_status    on public.profiles (verification_status);
create index if not exists idx_profiles_profession_cat  on public.profiles (profession_category);
create index if not exists idx_profiles_created_at      on public.profiles (created_at desc);

drop trigger if exists trg_profiles_updated on public.profiles;
create trigger trg_profiles_updated
  before update on public.profiles
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- certificates — uploaded documents per profile
-- ---------------------------------------------------------------------------
create table if not exists public.certificates (
  id          text primary key,
  profile_id  text not null references public.profiles(id) on delete cascade,
  title       text not null default '',
  issuer      text not null default '',
  year        text not null default '',
  image_url   text not null default '',
  created_at  timestamptz not null default now()
);

create index if not exists idx_certificates_profile_id on public.certificates (profile_id);

-- ---------------------------------------------------------------------------
-- reviews
-- ---------------------------------------------------------------------------
create table if not exists public.reviews (
  id                  text primary key,
  profile_id          text not null references public.profiles(id) on delete cascade,
  author              text not null default 'Житель Самашек',
  author_id           uuid references public.user_profiles(id) on delete set null,
  author_avatar_url   text,
  rating              numeric(2,1) not null check (rating between 0 and 5),
  text                text not null default '',
  created_at          date not null default current_date
);

create index if not exists idx_reviews_profile_id on public.reviews (profile_id, created_at desc);

-- ---------------------------------------------------------------------------
-- complaints
-- ---------------------------------------------------------------------------
create table if not exists public.complaints (
  id            text primary key,
  profile_id    text not null references public.profiles(id) on delete cascade,
  target_user_id uuid references public.user_profiles(id) on delete set null,
  author_id     uuid not null references public.user_profiles(id) on delete cascade,
  author_name   text not null default '',
  reason        text not null check (char_length(reason) between 1 and 500),
  status        text not null default 'open'
    check (status in ('open', 'dismissed', 'resolved')),
  created_at    date not null default current_date
);

create index if not exists idx_complaints_status on public.complaints (status, created_at desc);
create index if not exists idx_complaints_profile on public.complaints (profile_id);
-- <<<<<< 02-tables.sql <<<<<<

-- >>>>>> 03-aux-tables.sql (3.5 kB) >>>>>>
-- =============================================================================
-- Step 03 / 07 — Auxiliary tables
-- (house_addresses, notifications, donations, project_support)
-- =============================================================================
-- Paste into SQL Editor and Run.
-- After this step you should have 9 tables total.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- house_addresses — admin-managed Samashki address book
-- ---------------------------------------------------------------------------
create table if not exists public.house_addresses (
  id             text primary key,
  street         text not null,
  house_number   text not null default '',
  full_address   text not null,
  lat            numeric(10,7) not null,
  lng            numeric(10,7) not null,
  postal_code    text not null default '366602',
  is_not_house   boolean not null default false,
  category       text,
  created_at     timestamptz not null default now()
);

create index if not exists idx_house_addresses_street on public.house_addresses (street);
create index if not exists idx_house_addresses_category on public.house_addresses (category);

-- ---------------------------------------------------------------------------
-- notifications
-- ---------------------------------------------------------------------------
create table if not exists public.notifications (
  id            text primary key,
  recipient_id  uuid not null references public.user_profiles(id) on delete cascade,
  type          text not null default 'system'
    check (type in ('system', 'profile_hidden', 'profile_visible', 'user_blocked', 'user_unblocked')),
  title         text not null default 'Уведомление',
  message       text not null default '',
  is_read       boolean not null default false,
  created_at    timestamptz not null default now()
);

create index if not exists idx_notifications_recipient on public.notifications (recipient_id, created_at desc);
create index if not exists idx_notifications_unread on public.notifications (recipient_id) where not is_read;

-- ---------------------------------------------------------------------------
-- donations — CloudTips ledger (idempotent by operation_id)
-- ---------------------------------------------------------------------------
create table if not exists public.donations (
  operation_id  text primary key,
  amount        numeric(12,2) not null check (amount > 0),
  currency      text not null default 'RUB',
  sender        text,
  label         text,
  received_at   timestamptz not null,
  raw_payload   jsonb not null default '{}'::jsonb,
  created_at    timestamptz not null default now()
);

create index if not exists idx_donations_received_at on public.donations (received_at);

-- ---------------------------------------------------------------------------
-- project_support — aggregated monthly donation progress
-- ---------------------------------------------------------------------------
create table if not exists public.project_support (
  month_key        text primary key, -- e.g. '2026-08'
  collected_rub    numeric(12,2) not null default 0,
  other_costs_rub  numeric(12,2) not null default 500,
  updated_at       timestamptz not null default now()
);

drop trigger if exists trg_project_support_updated on public.project_support;
create trigger trg_project_support_updated
  before update on public.project_support
  for each row execute function public.touch_updated_at();
-- <<<<<< 03-aux-tables.sql <<<<<<

-- >>>>>> 04-storage-and-rls-enable.sql (1.5 kB) >>>>>>
-- =============================================================================
-- Step 04 / 07 — Storage bucket + enable RLS on all tables
-- =============================================================================
-- Paste into SQL Editor and Run.
-- This step does NOT yet define policies — that is step 05.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. Storage: profile-media bucket
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('profile-media', 'profile-media', true)
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- 2. Enable RLS on all tables (policies come in step 05)
-- ---------------------------------------------------------------------------
alter table public.user_profiles   enable row level security;
alter table public.profiles         enable row level security;
alter table public.certificates     enable row level security;
alter table public.reviews          enable row level security;
alter table public.complaints       enable row level security;
alter table public.house_addresses  enable row level security;
alter table public.notifications    enable row level security;
alter table public.donations        enable row level security;
alter table public.project_support  enable row level security;
-- <<<<<< 04-storage-and-rls-enable.sql <<<<<<

-- >>>>>> 05-rls-policies.sql (8.0 kB) >>>>>>
-- =============================================================================
-- Step 05 / 07 — Row Level Security policies
-- =============================================================================
-- Paste into SQL Editor and Run.
--
-- IMPORTANT: auth.uid() in Supabase returns uuid but in older setups it
-- may be text. All comparisons in this file cast auth.uid() to uuid
-- explicitly so policies work regardless of the project's auth.uid()
-- declaration.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- user_profiles
-- ---------------------------------------------------------------------------
drop policy if exists "user_profiles self select" on public.user_profiles;
create policy "user_profiles self select"
  on public.user_profiles for select
  using (auth.uid()::text = id::text or is_admin_email());

drop policy if exists "user_profiles self insert" on public.user_profiles;
create policy "user_profiles self insert"
  on public.user_profiles for insert
  with check (auth.uid()::text = id::text);

drop policy if exists "user_profiles self update" on public.user_profiles;
create policy "user_profiles self update"
  on public.user_profiles for update
  using (auth.uid()::text = id::text)
  with check (auth.uid()::text = id::text);

drop policy if exists "user_profiles admin update" on public.user_profiles;
create policy "user_profiles admin update"
  on public.user_profiles for update
  using (is_admin_email())
  with check (is_admin_email());

-- ---------------------------------------------------------------------------
-- profiles — public catalogue
-- ---------------------------------------------------------------------------
drop policy if exists "profiles public read" on public.profiles;
create policy "profiles public read"
  on public.profiles for select
  using (
    not (is_hidden or is_banned)
    or auth.uid()::text = owner_id::text
    or is_admin_email()
  );

drop policy if exists "profiles owner insert" on public.profiles;
create policy "profiles owner insert"
  on public.profiles for insert
  with check (auth.uid()::text = owner_id::text or owner_id is null);

drop policy if exists "profiles owner update" on public.profiles;
create policy "profiles owner update"
  on public.profiles for update
  using (auth.uid()::text = owner_id::text)
  with check (auth.uid()::text = owner_id::text);

drop policy if exists "profiles admin update" on public.profiles;
create policy "profiles admin update"
  on public.profiles for update
  using (is_admin_email())
  with check (is_admin_email());

drop policy if exists "profiles owner delete" on public.profiles;
create policy "profiles owner delete"
  on public.profiles for delete
  using (
    (auth.uid()::text = owner_id::text and not is_personal)
    or is_admin_email()
  );

-- ---------------------------------------------------------------------------
-- certificates
-- ---------------------------------------------------------------------------
drop policy if exists "certificates public read" on public.certificates;
create policy "certificates public read"
  on public.certificates for select
  using (true);

drop policy if exists "certificates owner write" on public.certificates;
create policy "certificates owner write"
  on public.certificates for all
  using (
    exists (select 1 from public.profiles p where p.id = certificates.profile_id and p.owner_id::text = auth.uid()::text)
    or is_admin_email()
  )
  with check (
    exists (select 1 from public.profiles p where p.id = certificates.profile_id and p.owner_id::text = auth.uid()::text)
    or is_admin_email()
  );

-- ---------------------------------------------------------------------------
-- reviews
-- ---------------------------------------------------------------------------
drop policy if exists "reviews public read" on public.reviews;
create policy "reviews public read"
  on public.reviews for select
  using (true);

drop policy if exists "reviews author write" on public.reviews;
create policy "reviews author write"
  on public.reviews for insert
  with check (auth.uid()::text = author_id::text);

drop policy if exists "reviews author delete" on public.reviews;
create policy "reviews author delete"
  on public.reviews for delete
  using (auth.uid()::text = author_id::text or is_admin_email());

-- ---------------------------------------------------------------------------
-- complaints
-- ---------------------------------------------------------------------------
drop policy if exists "complaints author read" on public.complaints;
create policy "complaints author read"
  on public.complaints for select
  using (auth.uid()::text = author_id::text or is_admin_email());

drop policy if exists "complaints author insert" on public.complaints;
create policy "complaints author insert"
  on public.complaints for insert
  with check (auth.uid()::text = author_id::text);

drop policy if exists "complaints admin update" on public.complaints;
create policy "complaints admin update"
  on public.complaints for update
  using (is_admin_email())
  with check (is_admin_email());

-- ---------------------------------------------------------------------------
-- house_addresses
-- ---------------------------------------------------------------------------
drop policy if exists "house_addresses public read" on public.house_addresses;
create policy "house_addresses public read"
  on public.house_addresses for select
  using (true);

drop policy if exists "house_addresses admin write" on public.house_addresses;
create policy "house_addresses admin write"
  on public.house_addresses for all
  using (is_admin_email())
  with check (is_admin_email());

-- ---------------------------------------------------------------------------
-- notifications
-- ---------------------------------------------------------------------------
drop policy if exists "notifications self read" on public.notifications;
create policy "notifications self read"
  on public.notifications for select
  using (auth.uid()::text = recipient_id::text);

drop policy if exists "notifications self update" on public.notifications;
create policy "notifications self update"
  on public.notifications for update
  using (auth.uid()::text = recipient_id::text)
  with check (auth.uid()::text = recipient_id::text);

drop policy if exists "notifications admin insert" on public.notifications;
create policy "notifications admin insert"
  on public.notifications for insert
  with check (is_admin_email() or auth.uid()::text = recipient_id::text);

-- ---------------------------------------------------------------------------
-- donations + project_support — public read, service-role writes
-- ---------------------------------------------------------------------------
drop policy if exists "donations public read" on public.donations;
create policy "donations public read"
  on public.donations for select
  using (true);

drop policy if exists "project_support public read" on public.project_support;
create policy "project_support public read"
  on public.project_support for select
  using (true);

-- ---------------------------------------------------------------------------
-- Storage RLS policies
-- ---------------------------------------------------------------------------
drop policy if exists "profile-media read" on storage.objects;
create policy "profile-media read"
  on storage.objects
  for select
  using (bucket_id = 'profile-media');

drop policy if exists "profile-media owner write" on storage.objects;
create policy "profile-media owner write"
  on storage.objects
  for insert
  with check (
    bucket_id = 'profile-media'
    and auth.role() = 'authenticated'
    and (storage.foldername(name))[1] in ('avatars', 'documents')
    and (storage.foldername(name))[2] like (auth.uid()::text || '-%')
  );

drop policy if exists "profile-media owner delete" on storage.objects;
create policy "profile-media owner delete"
  on storage.objects
  for delete
  using (
    bucket_id = 'profile-media'
    and (storage.foldername(name))[2] like (auth.uid()::text || '-%')
  );
-- <<<<<< 05-rls-policies.sql <<<<<<

-- >>>>>> 06-realtime-and-views.sql (4.3 kB) >>>>>>
-- =============================================================================
-- Step 06 / 07 — Realtime publication + convenience views
-- =============================================================================
-- Paste into SQL Editor and Run.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. Realtime: attach tables to supabase_realtime publication
-- ---------------------------------------------------------------------------
-- Without this, the postgres_changes channels in the client
-- (ProfilesProvider, NotificationsProvider) are silent.
--
-- DO block makes each ALTER idempotent: if the table is already a
-- member, the EXCEPTION block swallows the duplicate error so re-running
-- this file (or running the bundled all-in-one.sql twice) is safe.
do $$
begin
  begin alter publication supabase_realtime add table public.profiles; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.user_profiles; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.complaints; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.notifications; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.house_addresses; exception when duplicate_object then null; end;
end $$;

-- ---------------------------------------------------------------------------
-- 2. Convenience views
-- ---------------------------------------------------------------------------

-- Public catalog view: only visible profiles (not hidden / not banned),
-- augmented with the owner's email and block status for admin filtering.
--
-- Cast BOTH sides to text for the join. On this Supabase project
-- user_profiles.id is text while profiles.owner_id is uuid. The text
-- side stays text; the uuid side is text-cast so the comparison
-- succeeds regardless of which side is which type.
--
-- security_invoker = true so the view respects RLS of the underlying
-- tables (otherwise SECURITY DEFINER would run as the view owner and
-- bypass policies — flagged by Supabase Security Advisor).
create or replace view public.v_public_profiles
  with (security_invoker = true) as
select
  p.*,
  u.email        as owner_email,
  u.is_blocked   as owner_is_blocked
from public.profiles p
left join public.user_profiles u on u.id::text = p.owner_id::text
where not (p.is_hidden or p.is_banned);

-- Admin dashboard view: same as above but includes hidden/banned.
create or replace view public.v_all_profiles
  with (security_invoker = true) as
select
  p.*,
  u.email        as owner_email,
  u.is_blocked   as owner_is_blocked
from public.profiles p
left join public.user_profiles u on u.id::text = p.owner_id::text;

-- Public users list for /admin → users tab.
create or replace view public.v_user_directory
  with (security_invoker = true) as
select
  u.id,
  u.email,
  u.full_name,
  u.avatar_url,
  u.is_admin,
  u.is_blocked,
  u.created_at,
  coalesce(c.profiles_total, 0) as profile_count,
  coalesce(c.hidden_total, 0)   as hidden_count
from public.user_profiles u
left join (
  select
    owner_id,
    count(*)                       as profiles_total,
    count(*) filter (where is_hidden) as hidden_total
  from public.profiles
  group by owner_id
) c on c.owner_id::text = u.id::text;

-- Aggregate donation progress for the current month (Europe/Moscow).
create or replace view public.v_current_donations
  with (security_invoker = true) as
select
  coalesce(sum(amount), 0)::numeric(12,2) as total_rub,
  count(*)                                as donations_count
from public.donations
where received_at >= date_trunc('month', now() at time zone 'Europe/Moscow')
  and received_at <  date_trunc('month', now() at time zone 'Europe/Moscow') + interval '1 month';

-- ---------------------------------------------------------------------------
-- 3. Extra indexes
-- ---------------------------------------------------------------------------
create index if not exists idx_profiles_photos_gin
  on public.profiles using gin (photos jsonb_path_ops);

create index if not exists idx_profiles_public_specialist
  on public.profiles (created_at desc)
  where not is_hidden and not is_banned and is_specialist;
-- <<<<<< 06-realtime-and-views.sql <<<<<<

-- >>>>>> 07-triggers.sql (5.1 kB) >>>>>>
-- =============================================================================
-- Step 07 / 07 — Counter triggers
-- (rating / review_count on profiles, profile_count on user_profiles)
-- =============================================================================
-- Paste into SQL Editor and Run LAST, after all tables exist.
-- If this step is the one that errors with "uuid = text", please share
-- the exact error message + line number.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- reviews -> profiles.rating / profiles.review_count
-- ---------------------------------------------------------------------------
create or replace function public.recompute_profile_rating(target_id text)
returns void
language sql
security definer
set search_path = public
as $$
  -- profiles.id is text (e.g. 'personal-<uuid>'), so this works as-is.
  update public.profiles
     set rating = coalesce((select round(avg(rating)::numeric, 1)
                            from public.reviews where profile_id = target_id), 0),
         review_count = (select count(*) from public.reviews where profile_id = target_id),
         updated_at = now()
   where id = target_id;
$$;

revoke all on function public.recompute_profile_rating(text) from public;
grant execute on function public.recompute_profile_rating(text) to authenticated, service_role;

create or replace function public.trg_recompute_rating()
returns trigger
language plpgsql
as $$
begin
  if (tg_op = 'DELETE') then
    perform public.recompute_profile_rating(old.profile_id);
    return old;
  else
    perform public.recompute_profile_rating(new.profile_id);
    if (tg_op = 'UPDATE' and old.profile_id is distinct from new.profile_id) then
      perform public.recompute_profile_rating(old.profile_id);
    end if;
    return new;
  end if;
end;
$$;

drop trigger if exists trg_reviews_after_insert on public.reviews;
create trigger trg_reviews_after_insert
  after insert on public.reviews
  for each row execute function public.trg_recompute_rating();

drop trigger if exists trg_reviews_after_update on public.reviews;
create trigger trg_reviews_after_update
  after update on public.reviews
  for each row execute function public.trg_recompute_rating();

drop trigger if exists trg_reviews_after_delete on public.reviews;
create trigger trg_reviews_after_delete
  after delete on public.reviews
  for each row execute function public.trg_recompute_rating();

-- ---------------------------------------------------------------------------
-- profiles -> user_profiles.profile_count
--
-- The user_profiles table on this project does NOT have a profile_count
-- column — the count is derived in the Next.js client (ProfilesProvider
-- sets user.profileCount = profiles.filter(p => p.ownerId === user.id).length
-- on every load, merge and update). Trying to UPDATE a missing column
-- here raised "column \"profile_count\" of relation \"user_profiles\" does
-- not exist" on every profile insert / update / delete, which also
-- blocked delete operations on specialist profiles.
--
-- We keep the function and triggers so any downstream code that calls
-- recompute_user_profile_count() still resolves, but the body is a
-- no-op (a NOTICE in the server log lets you confirm the trigger is
-- actually firing).
-- ---------------------------------------------------------------------------
create or replace function public.recompute_user_profile_count(target_user uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  raise notice 'recompute_user_profile_count called for % — counter is maintained client-side, skipping', target_user;
end;
$$;

revoke all on function public.recompute_user_profile_count(uuid) from public;
grant execute on function public.recompute_user_profile_count(uuid) to authenticated, service_role;

create or replace function public.trg_recompute_user_count()
returns trigger
language plpgsql
as $$
begin
  if (tg_op = 'DELETE') then
    if (old.owner_id is not null) then
      perform public.recompute_user_profile_count(old.owner_id);
    end if;
    return old;
  else
    if (new.owner_id is not null) then
      perform public.recompute_user_profile_count(new.owner_id);
    end if;
    if (tg_op = 'UPDATE' and old.owner_id is distinct from new.owner_id and old.owner_id is not null) then
      perform public.recompute_user_profile_count(old.owner_id);
    end if;
    return new;
  end if;
end;
$$;

drop trigger if exists trg_profiles_after_insert on public.profiles;
create trigger trg_profiles_after_insert
  after insert on public.profiles
  for each row execute function public.trg_recompute_user_count();

drop trigger if exists trg_profiles_after_update on public.profiles;
create trigger trg_profiles_after_update
  after update on public.profiles
  for each row execute function public.trg_recompute_user_count();

drop trigger if exists trg_profiles_after_delete on public.profiles;
create trigger trg_profiles_after_delete
  after delete on public.profiles
  for each row execute function public.trg_recompute_user_count();
-- <<<<<< 07-triggers.sql <<<<<<

-- >>>>>> 08-seed.sql (1.0 kB) >>>>>>
-- =============================================================================
-- Step 08 / 08 — Seed initial data (Samashki address book)
-- =============================================================================
-- Previously this step bulk-inserted ~75 house numbers into
-- public.house_addresses so the /map page would have something to render.
-- That made the admin's "delete everything" workflow impossible: the
-- next `db:build-all` would re-seed them.
--
-- The address book is now 100% admin-managed: when the project is
-- deployed for the first time, public.house_addresses starts empty and
-- the admin fills it from the /admin panel. The /map page already
-- handles an empty list correctly (it just shows the 6 address
-- categories and no houses).
--
-- This file is intentionally empty; it's kept as step 08 so the
-- pipeline doesn't have to renumber the other files.
-- =============================================================================
-- <<<<<< 08-seed.sql <<<<<<

-- >>>>>> 09-fix-reviews-author-id.sql (1.1 kB) >>>>>>
-- =============================================================================
-- Step 09 — Add missing author_id column to public.reviews
-- =============================================================================
-- Some Supabase projects have a public.reviews table that was created before
-- step 02 introduced the author_id column. The RLS policies and the Next.js
-- client code both reference reviews.author_id, so the column is required.
--
-- After step 10 (standardize ids to uuid) the column type is uuid. If you
-- haven't run step 10 yet on a project where user_profiles.id is text, you
-- can run this step with type text instead — but the more durable fix is
-- to run step 10 once and use the uuid variant.
--
-- This step is idempotent and safe to re-run. Existing rows get NULL.
-- =============================================================================

alter table public.reviews
  add column if not exists author_id uuid references public.user_profiles(id) on delete set null;

create index if not exists idx_reviews_author_id on public.reviews (author_id);
-- <<<<<< 09-fix-reviews-author-id.sql <<<<<<

-- >>>>>> 10-standardize-ids-to-uuid.sql (9.5 kB) >>>>>>
-- =============================================================================
-- Step 10 — Standardize all id columns to uuid
-- =============================================================================
-- This project's tables were originally created with text id columns
-- (because auth.uid() used to return text on this Supabase instance).
-- We're migrating everything to uuid to match the standard Supabase
-- schema and remove the need for ::text casts in RLS.
--
-- This step is fully idempotent and safe to re-run on any state:
--   * If a column is already uuid, ALTER COLUMN … TYPE uuid USING col::uuid
--     is a no-op (Postgres skips the rewrite when types match).
--   * If a FK already exists with the right name, drop constraint
--     if exists is a no-op; add constraint below either succeeds or
--     is a no-op if the same constraint already exists.
--   * If a column has non-uuid text in it, the USING col::uuid cast
--     will fail loudly so we can fix the data manually.
--
-- Pre-conditions (verified before this step is shipped):
--   * Every row in public.user_profiles.id is a valid UUID string
--   * The same is true for profiles.owner_id, complaints.author_id,
--     complaints.target_user_id, notifications.recipient_id and
--     reviews.author_id (confirmed via information_schema.columns +
--     sample SELECTs)
--   * auth.users.id is already uuid (we never touch that table)
--
-- Order matters:
--   1. Drop every RLS policy that references any of the columns we are
--      about to convert. Postgres refuses to ALTER a column that is
--      referenced by a policy (ERROR 0A000), so we must drop them first.
--      step 05 will recreate them with the new (uuid) types.
--   2. Drop the convenience views that SELECT from those columns for the
--      same reason (Postgres raises "cannot alter type of a column used
--      by a view or rule" otherwise). step 06 will recreate them after
--      the type change.
--   3. Drop every FK that points at user_profiles.id or at any of the
--      columns we are about to convert, so the ALTER COLUMN can run
--      without the type-mismatch error described in the
--      "reviews_author_id_fkey cannot be implemented" issue.
--   4. ALTER COLUMN with USING col::uuid (idempotent: same-type ALTER
--      is a no-op).
--   5. Recreate the FKs as NOT VALID (so the conversion is fast) and
--      VALIDATE them all at the end.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 0a) Drop every RLS policy in the public schema. We don't try to
--     limit this to specific tables because policies can reference
--     columns from other tables via sub-queries (e.g.
--     'certificates owner write' depends on profiles.owner_id through
--     'exists (select … p.owner_id = auth.uid())'), and Postgres
--     blocks ALTER on any column that appears in any policy on any
--     table in the schema. step 05 will recreate them at the end of
--     the migration.
-- ---------------------------------------------------------------------------
do $$
declare
  pol record;
begin
  for pol in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
  loop
    execute format('drop policy if exists %I on public.%I', pol.policyname, pol.tablename);
  end loop;
end $$;

-- ---------------------------------------------------------------------------
-- 0b) Drop the convenience views defined in step 06.
-- ---------------------------------------------------------------------------
drop view if exists public.v_public_profiles;
drop view if exists public.v_all_profiles;
drop view if exists public.v_user_directory;
drop view if exists public.v_current_donations;

-- ---------------------------------------------------------------------------
-- 0c) Drop every FK that points at user_profiles.id or at any of the
--     columns we are about to convert. We don't try to be clever about
--     which FKs exist; we drop the 5 known names and recreate them at
--     the end. drop constraint if exists makes each line a no-op when
--     the FK was already dropped in a previous run.
-- ---------------------------------------------------------------------------
alter table public.profiles      drop constraint if exists profiles_owner_id_fkey;
alter table public.reviews       drop constraint if exists reviews_author_id_fkey;
alter table public.complaints    drop constraint if exists complaints_author_id_fkey;
alter table public.complaints    drop constraint if exists complaints_target_user_id_fkey;
alter table public.notifications drop constraint if exists notifications_recipient_id_fkey;

-- ---------------------------------------------------------------------------
-- 1) user_profiles.id → uuid
--     ALTER COLUMN … TYPE uuid USING id::uuid is a no-op when the column
--     is already uuid, so this is safe on a partially-migrated project.
-- ---------------------------------------------------------------------------
alter table public.user_profiles
  alter column id type uuid using id::uuid;

-- ---------------------------------------------------------------------------
-- 2) profiles.owner_id → uuid
-- ---------------------------------------------------------------------------
alter table public.profiles
  alter column owner_id type uuid using owner_id::uuid;
alter table public.profiles
  add constraint profiles_owner_id_fkey
  foreign key (owner_id) references public.user_profiles(id) on delete cascade
  not valid;

-- ---------------------------------------------------------------------------
-- 3) reviews.author_id → uuid
-- ---------------------------------------------------------------------------
alter table public.reviews
  alter column author_id type uuid using author_id::uuid;
alter table public.reviews
  add constraint reviews_author_id_fkey
  foreign key (author_id) references public.user_profiles(id) on delete set null
  not valid;

-- ---------------------------------------------------------------------------
-- 4) complaints.author_id + target_user_id → uuid
-- ---------------------------------------------------------------------------
alter table public.complaints
  alter column author_id     type uuid using author_id::uuid;
alter table public.complaints
  alter column target_user_id type uuid using target_user_id::uuid;
alter table public.complaints
  add constraint complaints_author_id_fkey
  foreign key (author_id) references public.user_profiles(id) on delete cascade
  not valid;
alter table public.complaints
  add constraint complaints_target_user_id_fkey
  foreign key (target_user_id) references public.user_profiles(id) on delete set null
  not valid;

-- ---------------------------------------------------------------------------
-- 5) notifications.recipient_id → uuid
-- ---------------------------------------------------------------------------
alter table public.notifications
  alter column recipient_id type uuid using recipient_id::uuid;
alter table public.notifications
  add constraint notifications_recipient_id_fkey
  foreign key (recipient_id) references public.user_profiles(id) on delete cascade
  not valid;

-- ---------------------------------------------------------------------------
-- 6) Validate the FKs we just re-added. VALIDATE CONSTRAINT is a no-op
--    if the constraint is already validated, so this is safe on a
--    project where these FKs already existed.
-- ---------------------------------------------------------------------------
alter table public.profiles      validate constraint profiles_owner_id_fkey;
alter table public.reviews       validate constraint reviews_author_id_fkey;
alter table public.complaints    validate constraint complaints_author_id_fkey;
alter table public.complaints    validate constraint complaints_target_user_id_fkey;
alter table public.notifications validate constraint notifications_recipient_id_fkey;

-- ---------------------------------------------------------------------------
-- 7) Recreate the convenience views (same definitions as step 06, but
--    with the ::text casts removed now that the join keys are uuid).
-- ---------------------------------------------------------------------------
create or replace view public.v_public_profiles
  with (security_invoker = true) as
select
  p.*,
  u.email        as owner_email,
  u.is_blocked   as owner_is_blocked
from public.profiles p
left join public.user_profiles u on u.id = p.owner_id
where not (p.is_hidden or p.is_banned);

create or replace view public.v_all_profiles
  with (security_invoker = true) as
select
  p.*,
  u.email        as owner_email,
  u.is_blocked   as owner_is_blocked
from public.profiles p
left join public.user_profiles u on u.id = p.owner_id;

create or replace view public.v_user_directory
  with (security_invoker = true) as
select
  u.id,
  u.email,
  u.full_name,
  u.avatar_url,
  u.is_admin,
  u.is_blocked,
  u.created_at,
  coalesce(c.profiles_total, 0) as profile_count,
  coalesce(c.hidden_total, 0)   as hidden_count
from public.user_profiles u
left join (
  select
    owner_id,
    count(*)                          as profiles_total,
    count(*) filter (where is_hidden) as hidden_total
  from public.profiles
    group by owner_id
) c on c.owner_id = u.id;

create or replace view public.v_current_donations
  with (security_invoker = true) as
select
  coalesce(sum(amount), 0)::numeric(12,2) as total_rub,
  count(*)                                as donations_count
from public.donations
where received_at >= date_trunc('month', now() at time zone 'Europe/Moscow')
  and received_at <  date_trunc('month', now() at time zone 'Europe/Moscow') + interval '1 month';
-- <<<<<< 10-standardize-ids-to-uuid.sql <<<<<<

-- >>>>>> 11-profiles-rls-and-count.sql (7.3 kB) >>>>>>
-- =============================================================================
-- Step 11 — Fix profiles RLS to hide other users' personal profiles, and
--           add a server-side profile_count view for the admin panel.
-- =============================================================================
-- Run AFTER step 10. Idempotent.
--
-- Why this step exists:
--   The previous RLS policy "profiles public read" was:
--
--     using (
--       not (is_hidden or is_banned)
--       or auth.uid()::text = owner_id::text
--       or is_admin_email()
--     );
--
--   That means EVERYONE could SELECT every non-hidden / non-banned
--   profile, including other users' personal profiles (is_personal=true).
--   The UI happened to filter them out client-side, but a curious user
--   could read them straight from the database with curl + the anon key.
--   Worse, the Next.js client was caching them in localStorage, so they
--   leaked across sessions and across browsers (the "phantom profile"
--   bug).
--
--   The fix is to enforce the same rule on the server that we wanted on
--   the client: only the owner, the admin, and no one else can see a
--   personal profile. Non-personal profiles (specialists, public
--   listings) stay visible to everyone as before.
--
--   We also add a SQL view that returns user_profiles with a
--   server-computed `profile_count`. The admin panel reads from this
--   view instead of counting client-side, so the count is always
--   correct (and always >= 1 for users with a personal profile).
-- =============================================================================


-- ---------------------------------------------------------------------------
-- 1) Tighten the public-read RLS policy to hide other users' personal
--    profiles. The owner and the admin still see them.
-- ---------------------------------------------------------------------------
drop policy if exists "profiles public read" on public.profiles;
create policy "profiles public read"
  on public.profiles for select
  using (
    -- Anyone can see a non-personal profile that is not hidden / banned.
    (not is_personal and not (is_hidden or is_banned))
    -- The owner can always see their own rows, including their personal
    -- profile and any hidden / banned rows of theirs.
    or auth.uid()::text = owner_id::text
    -- Admins can see everything for moderation purposes.
    or is_admin_email()
  );


-- ---------------------------------------------------------------------------
-- 2) View: user_profiles with a server-computed profile_count.
--    Uses security_invoker = true so the calling user's RLS still applies
--    when they query the view (admins see real counts for everyone,
--    regular users would only see their own row through the underlying
--    user_profiles RLS — though in practice this view is only used by
--    the admin panel).
-- ---------------------------------------------------------------------------
create or replace view public.v_users_with_profile_count
  with (security_invoker = true) as
select
  u.id,
  u.email,
  u.full_name,
  u.avatar_url,
  u.is_admin,
  u.is_blocked,
  u.created_at,
  u.settlement,
  coalesce(c.profiles_total, 0) as profile_count,
  coalesce(c.hidden_total, 0)   as hidden_count
from public.user_profiles u
left join (
  select
    owner_id,
    count(*)                          as profiles_total,
    count(*) filter (where is_hidden or is_banned) as hidden_total
  from public.profiles
  where owner_id is not null
  group by owner_id
) c on c.owner_id = u.id;

comment on view public.v_users_with_profile_count is
  'user_profiles joined with a server-computed count of their profiles. '
  'Used by the admin panel. Read it with the service role to bypass '
  'user_profiles RLS for everyone, or as a regular user to see only '
  'your own row.';


-- ---------------------------------------------------------------------------
-- 3) Convenience RPC: create a personal profile for the calling user
--    if one doesn't already exist. Returns the existing row when
--    present (idempotent). Runs with security definer so it can
--    insert into profiles on behalf of the user without us having to
--    duplicate the owner-insert RLS logic in the application.
-- ---------------------------------------------------------------------------
create or replace function public.ensure_personal_profile(
  p_full_name text,
  p_avatar_url text default '',
  p_phone text default ''
)
returns public.profiles
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_existing public.profiles;
  v_personal_id text;
  v_row public.profiles;
begin
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  v_personal_id := 'personal-' || v_user_id::text;

  -- Idempotency: if the canonical personal row already exists,
  -- return it. This is the only row we keep; we never spawn
  -- duplicates (the previous bug).
  select * into v_existing
    from public.profiles
   where id = v_personal_id;
  if found then
    return v_existing;
  end if;

  -- Defensive: if there are OTHER is_personal=true rows for this
  -- owner (e.g. created by an older client), we still don't error
  -- — we just create the canonical one alongside. The admin can
  -- clean up duplicates later.
  insert into public.profiles (
    id,
    owner_id,
    full_name,
    avatar_url,
    is_specialist,
    is_personal,
    bio,
    workplace_address,
    workplace_coords,
    phone,
    hide_phone,
    same_as_phone_whatsapp,
    settlement
  ) values (
    v_personal_id,
    v_user_id,
    coalesce(nullif(trim(p_full_name), ''), 'Житель Даймохк'),
    coalesce(p_avatar_url, ''),
    false,
    true,
    'Житель Даймохк. Личная анкета.',
    'Даймохк',
    '{"lat":43.288024,"lng":45.298989}'::jsonb,
    coalesce(p_phone, ''),
    true,
    false,
    'Самашки'
  )
  returning * into v_row;

  return v_row;
end;
$$;

revoke all on function public.ensure_personal_profile(text, text, text) from public;
grant execute on function public.ensure_personal_profile(text, text, text) to authenticated;

comment on function public.ensure_personal_profile(text, text, text) is
  'Create the canonical personal profile (id = personal-<auth.uid()>) '
  'for the calling user if it does not already exist. Idempotent: '
  'returns the existing row when present. Used by the Next.js client '
  'as a single round-trip replacement for the previous in-memory '
  'auto-create flow.';


-- ---------------------------------------------------------------------------
-- 4) Convenience RPC: a server-side view of profiles for a given
--    owner (used by the admin panel to list a user's questionnaires).
--    Runs with security definer so the admin can list any user's
--    profiles without us having to grant admins a special SELECT
--    bypass.
-- ---------------------------------------------------------------------------
create or replace function public.list_profiles_for_owner(p_owner_id uuid)
returns setof public.profiles
language sql
security definer
set search_path = public
stable
as $$
  select * from public.profiles where owner_id = p_owner_id
  order by is_personal desc, created_at desc;
$$;

revoke all on function public.list_profiles_for_owner(uuid) from public;
grant execute on function public.list_profiles_for_owner(uuid) to authenticated;
-- <<<<<< 11-profiles-rls-and-count.sql <<<<<<

-- >>>>>> 12-onboarding-trigger.sql (5.8 kB) >>>>>>
-- =============================================================================
-- Step 12 — Auto-create user_profiles + personal profile on signup
-- =============================================================================
-- Run AFTER step 11. Idempotent.
--
-- Why this step exists:
--   Before this step, the personal profile was created from the Next.js
--   client via /api/account/ensure-personal-profile. That worked in
--   theory, but had two problems:
--
--     1) If the user never opened the app, they had no user_profiles
--        row. The admin panel would not see them in the user list,
--        and the view v_users_with_profile_count would not return
--        them either.
--
--     2) If the client failed to call ensure-personal-profile (the
--        RPC was missing because step 11 hadn't been applied, for
--        example), the user had a user_profiles row but no
--        personal profile. Their profileCount stayed at 0.
--
--   The canonical Supabase fix for both is to put the onboarding
--   logic on the server, in an AFTER INSERT trigger on auth.users.
--   The trigger fires for every signup (Google OAuth, magic link,
--   email/password, etc.) and is the documented pattern in
--   supabase.com/docs/guides/auth/managing-user-data.
--
--   This step also backfills user_profiles and the personal profile
--   for any auth.users rows that already exist at the time of
--   execution, so admins that ran the project before this trigger
--   was added will get their personal profiles retroactively.
-- =============================================================================


-- ---------------------------------------------------------------------------
-- 1) A single SECURITY DEFINER function that handles all the onboarding
--    work: create user_profiles if missing, create the canonical
--    personal profile if missing. Both inserts go through the
--    SECURITY DEFINER role, which bypasses RLS so the trigger
--    doesn't get tangled up in self-insert RLS policies.
-- ---------------------------------------------------------------------------
create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_full_name text;
  v_avatar_url text;
  v_phone text;
  v_personal_id text;
  v_is_admin boolean;
begin
  v_full_name := coalesce(
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'name',
    ''
  );
  v_avatar_url := coalesce(new.raw_user_meta_data->>'avatar_url', '');
  v_phone := coalesce(new.phone, '');
  v_personal_id := 'personal-' || new.id::text;
  v_is_admin := lower(coalesce(new.email, '')) in (
    'mr.hamzik1026@gmail.com',
    'nabis95@gmail.com'
  );

  -- 1a) Create the user_profiles row if it doesn't exist.
  --     ON CONFLICT DO NOTHING is idempotent: re-running the
  --     trigger for the same user is a no-op.
  insert into public.user_profiles (
    id, email, full_name, avatar_url, phone, is_admin
  ) values (
    new.id, new.email, v_full_name, v_avatar_url, v_phone, v_is_admin
  )
  on conflict (id) do nothing;

  -- 1b) Create the canonical personal profile if it doesn't exist.
  --     Same idempotency trick.
  insert into public.profiles (
    id,
    owner_id,
    full_name,
    avatar_url,
    is_specialist,
    is_personal,
    bio,
    workplace_address,
    workplace_coords,
    phone,
    hide_phone,
    same_as_phone_whatsapp,
    settlement
  ) values (
    v_personal_id,
    new.id,
    v_full_name,
    v_avatar_url,
    false,
    true,
    'Житель Даймохк. Личная анкета.',
    'Даймохк',
    '{"lat":43.288024,"lng":45.298989}'::jsonb,
    v_phone,
    true,
    false,
    'Самашки'
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

-- The trigger function runs as SECURITY DEFINER (the table owner)
-- because we need to bypass RLS when inserting the new rows on
-- behalf of the new user. Without this, the "user_profiles self
-- insert" and "profiles owner insert" RLS policies would block the
-- inserts (because auth.uid() is the new user, but the role
-- executing the trigger is the function owner, not the new user).
-- We grant execute only to the postgres role, which is what the
-- trigger uses to invoke the function.

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_auth_user();


-- ---------------------------------------------------------------------------
-- 2) Backfill: every auth.users row that doesn't yet have a
--    user_profiles entry gets one; every auth.users row that
--    doesn't yet have a personal-<id> profile gets one.
--    Safe to re-run: ON CONFLICT DO NOTHING everywhere.
-- ---------------------------------------------------------------------------
insert into public.user_profiles (id, email, full_name, avatar_url, phone, is_admin)
select
  au.id,
  au.email,
  coalesce(au.raw_user_meta_data->>'full_name', au.raw_user_meta_data->>'name', ''),
  coalesce(au.raw_user_meta_data->>'avatar_url', ''),
  coalesce(au.phone, ''),
  lower(coalesce(au.email, '')) in (
    'mr.hamzik1026@gmail.com', 'nabis95@gmail.com'
  )
from auth.users au
on conflict (id) do nothing;

insert into public.profiles (
  id, owner_id, full_name, avatar_url, is_specialist, is_personal,
  bio, workplace_address, workplace_coords, phone, hide_phone,
  same_as_phone_whatsapp, settlement
)
select
  'personal-' || au.id::text,
  au.id,
  coalesce(au.raw_user_meta_data->>'full_name', au.raw_user_meta_data->>'name', 'Житель Даймохк'),
  coalesce(au.raw_user_meta_data->>'avatar_url', ''),
  false,
  true,
  'Житель Даймохк. Личная анкета.',
  'Даймохк',
  '{"lat":43.288024,"lng":45.298989}'::jsonb,
  coalesce(au.phone, ''),
  true,
  false,
  'Самашки'
from auth.users au
on conflict (id) do nothing;
-- <<<<<< 12-onboarding-trigger.sql <<<<<<

