-- =============================================================================
-- Step 08 / 08 — Seed initial data (Samashki address book)
-- =============================================================================
-- Previously this step bulk-inserted ~75 house numbers into
-- public.house_addresses so the /map page would have something to render.
-- That made the admin's "delete everything" workflow impossible: the
-- next `db:build-all` would re-seed them.
--
-- The address book is now 100% admin-managed: when the project is
-- deployed for the first time, public.house_addresses starts empty and
-- the admin fills it from the /admin panel. The /map page already
-- handles an empty list correctly (it just shows the 6 address
-- categories and no houses).
--
-- This file is intentionally empty; it's kept as step 08 so the
-- pipeline doesn't have to renumber the other files.
-- =============================================================================
